server {
    #Escucha su purto defecto de Nginx que es 80
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Fallback: cualquier ruta desconocida devuelve index.html

    location / {
        try_files $uri /index.html;
    }
     # Archivos estáticos con cacheo

    location ~* \.(?:ico|css|js|wasm|dll|png|jpg|jpeg|gif|svg)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
    # Gzip para reducir tamaño de archivos
    gzip on;
    gzip_disable "msie6";
    gzip_min_length 256;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/javascript application/json application/octet-stream application/wasm;
}
